### ISSUE TITLE
Bosh VMs are unable to communicate with bosh director on stemcell v1015

### ISSUE THREAD

**Issue by alexwo** [cloudfoundry-incubator/bosh-alicloud-cpi-release#25]
The Bosh agent is unable to communicate with director on stemcell v1015.
Probably due to stemcell issue around the registry interaction / support.

Impact:
Not possible to use bosh for doing any deployments.

**Comment by xiaozhu36** [comment]
Hi @alexwo This issue has been fixed by release 16 and stemcell 1016. Please update CPI 16 from #24 
 and stemcell 1016 from the following address:

Chinese Mainland：http://bosh.oss-cn-hangzhou.aliyuncs.com/light-bosh-stemcell-1016-alicloud-kvm-ubuntu-trusty-go_agent.tgz

Hong Kong and Oversea: http://bosh-(regionId).oss-(regionId).aliyuncs.com/light-bosh-stemcell-1016-alicloud-kvm-ubuntu-trusty-go_agent.tgz, like http://bosh-eu-central-1.oss-eu-central-1.aliyuncs.com/light-bosh-stemcell-1016-alicloud-kvm-ubuntu-trusty-go_agent.tgz

Release 16 sha1: dc63a7b28fa77294ae4c7305c85d9590ca690cd9

Thanks a lot

**Comment by ninja-at-work** [comment]
The newest cpi and stemcell (v1016) doesn't not solve our issue with deployments, the agent still won't start on "compilation" vm.
So we see in logs only countless amounts of attempts of bosh director to communicate with agent:
D, [2017-12-31T14:50:52 #28944] [compile_package(golang/03d27673d09c82e7a4183d651e6c293b4a501de7, bosh-alicloud-kvm-ubuntu-trusty-go_agent/1016)] DEBUG -- DirectorJobRunner: SENT: agent.2517d24b-30b4-4231-963b-469658c085f2 {"protocol":3,"method":"ping","arguments":[],"reply_to":"director.7c315cd4-dae6-42f2-9b9b-7cdeb23ee066.2517d24b-30b4-4231-963b-469658c085f2.aa0fbc0e-22cb-4b4f-ac10-7c6bc25d7503"}

We also tried to update bosh director with newest cpi/stemcell and in this case it also had a similar issue with agent; bosh-init fails with the following error:
Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-alicloud-kvm-ubuntu-trusty-go_agent/1016'... Finished (00:00:00)

Started deploying
 Waiting for the agent on VM 'i-gw82jrf5qf5u5ka83p4v'... Finished (00:00:00)
 Stopping jobs on instance 'unknown/0'... Finished (00:00:01)
 Unmounting disk 'd-gw82jrf5qf5u56gxbpvf'... Finished (00:00:10)
 Deleting VM 'i-gw82jrf5qf5u5ka83p4v'... Finished (00:00:38)
 Creating VM for instance 'bootstrap-bosh/0' from stemcell 'm-gw8czf04a5mdvqjpdksd'... Finished (00:01:28)
 Waiting for the agent on VM 'i-gw8bkq68l1qs6s2gnkf7' to be ready... Failed (00:09:59)
Failed deploying (00:12:24)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)
Deploying:
 Creating instance 'bootstrap-bosh/0':
   Waiting until instance is ready:
     Post https://mbus:<redacted>@10.128.1.10:6868/agent: dial tcp 10.128.1.10:6868: getsockopt: connection refused
Exit code 1

So it means that v1016 stemcell introduces a regression, because with the previous version (v1015) we were able to deploy bosh director at least.

Here is a table of combinations of cpi/stemcells versions we're tested:
CPI v1015 + Stemcell v1015 -> Bosh director can be deployed -> Component/Compilation vm is not working due agent issue
CPI v1016 + Stemcell v1015 -> Bosh director can be deployed -> Component/Compilation vm is not working due agent issue
CPI v1016 + Stemcell v1016 -> Bosh director is not working due agent issue
CPI v1016 + Stemcell v1016 -> Bosh director is not working due agent issue

**Comment by xiaozhu36** [comment]
Hi @ninja-at-work I am sorry for that. Please ensure you have specified key_pair_name and ssh_tunnel configure with private_key, and them are required in the version release 16 and stemcell 1016. 

In addition, please refer to the lastest manifest https://github.com/cloudfoundry/bosh-deployment/blob/master/bosh.yml and CPI configure https://github.com/aliyun/bosh-deployment/blob/master/alicloud/cpi.yml to configure your manifest.
